apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-app
  labels:
    app: youtube-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube-app
  template:
    metadata:
      labels:
        app: youtube-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: youtube-app
        # PHẢI KHỚP VỚI TÊN TRONG JENKINSFILE
        image: my-youtube-app:latest
        # QUAN TRỌNG: Để K8s lấy image từ máy local thay vì lên mạng tìm
        imagePullPolicy: "IfNotPresent" 
        ports:
        - containerPort: 3000
