apiVersion: v1
kind: Service
metadata:
  name: youtube-service
spec:
  selector:
    app: youtube-app
  ports:
    - protocol: TCP
      port: 80         # Port này khớp với lúc bạn tạo cluster k3d
      targetPort: 3000 # Port mà React đang chạy bên trong Pod
  type: LoadBalancer
